# Generated by Django 5.1.5 on 2026-01-04 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название книги')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BookTemplate',
        ),
        migrations.RemoveField(
            model_name='bookcover',
            name='dedication',
        ),
        migrations.RemoveField(
            model_name='bookpageanswer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='telegram_username_or_phone',
        ),
        migrations.AddField(
            model_name='bookdedication',
            name='text',
            field=models.TextField(default='', verbose_name='Текст посвящения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookcover',
            name='author_book',
            field=models.CharField(max_length=255, verbose_name='Автор на обложке'),
        ),
        migrations.AlterField(
            model_name='bookcover',
            name='template',
            field=models.CharField(choices=[('classic', 'Классический'), ('dark', 'Тёмный'), ('modern', 'Современный')], default='classic', max_length=50, verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='bookcover',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок на обложке'),
        ),
        migrations.AlterField(
            model_name='bookdedication',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='bookpageanswer',
            name='answer',
            field=models.TextField(verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='bookpageanswer',
            name='quiz',
            field=models.CharField(max_length=255, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='bookpagequestion',
            name='quiz',
            field=models.CharField(max_length=255, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='book',
            name='dedication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.bookdedication', verbose_name='Посвящение'),
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookcover',
            name='book',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_data', to='config.book'),
        ),
        migrations.AddField(
            model_name='bookpageanswer',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='config.book'),
        ),
    ]
