# Generated by Django 5.1.5 on 2026-01-04 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_book_delete_booktemplate_remove_bookcover_dedication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Завершено (Ждет проверки)'), ('printed', 'Напечатано')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='bookpagequestion',
            name='dedication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='config.bookdedication', verbose_name='Для кого (посвящение)'),
        ),
    ]
