# Generated by Django 5.1.5 on 2026-01-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_book_status_bookpagequestion_dedication'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpageanswer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/', verbose_name='Фотография'),
        ),
    ]
