# Generated by Django 5.1.5 on 2026-01-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_notification_sent',
            field=models.BooleanField(default=False, verbose_name='Уведомление отправлено'),
        ),
        migrations.AlterField(
            model_name='bookcover',
            name='template',
            field=models.CharField(choices=[('classic', 'Классический'), ('dark', 'Тёмный'), ('modern', 'Минималистичный')], default='classic', max_length=50, verbose_name='Шаблон'),
        ),
    ]
