# Generated by Django 5.2.4 on 2026-01-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_book_is_notification_sent_alter_bookcover_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gemini_api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Gemini API Key')),
                ('ai_question_count', models.IntegerField(default=5, verbose_name='Количество вопросов ИИ')),
                ('is_ai_enabled', models.BooleanField(default=True, verbose_name='ИИ включен')),
            ],
            options={
                'verbose_name': 'Настройки ИИ',
                'verbose_name_plural': 'Настройки ИИ',
            },
        ),
    ]
