# Generated by Django 5.2.4 on 2026-01-12 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_aisettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpagequestion',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_questions', to='config.book', verbose_name='Для книги'),
        ),
    ]
