# Generated by Django 5.2.4 on 2026-09-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_bookpagequestion_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcover',
            name='template',
            field=models.CharField(choices=[('classic', 'Классический'), ('dark', 'Тёмный'), ('modern', 'Минималистичный'), ('rose', 'Сад роз'), ('sage', 'Серебряные ветви'), ('wine', 'Бордовый бархат'), ('forest', 'Зелёный мрамор'), ('amber', 'Золотой вечер')], default='classic', max_length=50, verbose_name='Шаблон'),
        ),
    ]
