# Generated by Django 5.2.4 on 2026-09-12 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_cover_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Клиент подтвердил макет'),
        ),
        migrations.AddField(
            model_name='book',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='tracking_url',
            field=models.URLField(blank=True, verbose_name='Ссылка отслеживания'),
        ),
        migrations.AddField(
            model_name='bookpageanswer',
            name='focus_x',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='bookpageanswer',
            name='focus_y',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='bookpageanswer',
            name='image_fit',
            field=models.CharField(choices=[('contain', 'Целиком'), ('cover', 'Заполнить')], default='contain', max_length=10),
        ),
        migrations.AddField(
            model_name='bookpageanswer',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookpageanswer',
            name='rotation',
            field=models.PositiveIntegerField(choices=[(0, '0°'), (90, '90°'), (180, '180°'), (270, '270°')], default=0),
        ),
        migrations.AddField(
            model_name='bookpagequestion',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_link_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_link_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Завершено (Ждет проверки)'), ('printed', 'Напечатано'), ('printing', 'В печати'), ('shipped', 'Отправлена')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='BookStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Завершено (Ждет проверки)'), ('printed', 'Напечатано'), ('printing', 'В печати'), ('shipped', 'Отправлена')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telegram_sent', models.BooleanField(default=False)),
                ('delivery_error', models.CharField(blank=True, max_length=255)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='config.book')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
