# Generated by Django 5.2.4 on 2026-09-13 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_book_approved_at_book_revision_book_tracking_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок готовности'),
        ),
        migrations.AddField(
            model_name='book',
            name='internal_notes',
            field=models.TextField(blank=True, verbose_name='Внутренние заметки'),
        ),
        migrations.CreateModel(
            name='PageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='config.bookpageanswer')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
